language: ruby
before_install: "sudo apt-get update -qq"
install:
  - "sudo apt-get install -y libjpeg62"
  - "bundle install --without development --deployment --jobs=3 --retry=3"
script: "script/cibuild"
